spring:
  application:
     name: jilin
  datasource:
     url: 'jdbc:mysql://172.18.1.193:3306/?useUnicode=true&characterEncoding=utf-8&useSSL=false'
     username: jilin
     password: i5Jhi6C7FaJ5cXka
     driver-class: 'com.mysql.jdbc.Driver'
     database-name: jilin
     init-sql: mysql/init.sql
  thymeleaf:
     cache: false
     prefix: classpath:/templates/
     suffix: .html
     encoding: UTF-8
     content-type: text/html
     mode: HTML5
  data:
     elasticsearch:
       cluster-name: docker-cluster
       cluster-nodes: 172.18.1.193:9300

server:
  port: 80
    
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    
files:
  path: /root/files

es:
  endpoint: 172.18.1.193:9200
